# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:


services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    #bind:
    #    Herisson\Service\Message: '@herisson.service.message'

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  Herisson\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  Herisson\Controller\:
    resource: '../src/Controller/'
    tags: ['controller.service_arguments']
    #calls:
    #    - [setContainer, ["@service_container"]]

  Herisson\Service\:
    resource:
      - '../src/Service/'
#      - '../src/Repository/'
      - '../tests/src/Service/'
    tags: ['controller.service_arguments']
    #calls:
    #    - [setContainer, ["@service_container"]]


  Herisson\Repository\BookmarkRepository:
    arguments:
      - '@Doctrine\Common\Persistence\ManagerRegistry'
      - Herisson\Entity\Bookmark


  Herisson\Service\Network\GrabberInterface: '@Herisson\Service\Network\GrabberGuzzleMock'
  Herisson\Repository\BookmarkRepositoryInterface: '@Herisson\Repository\BookmarkRepositoryMock'


#bookmark_repository:
#  class: Herisson\Repository\BookmarkRepositoryInterface
#  factory: ["@doctrine", getRepository]
#  arguments:
#    - '@Herisson\Repository\BookmarkRepository'


#use_cases:
#  class: Herisson\Repository\BookmarkRepositoryInterface
#  arguments:
#    - "@bookmark_repository"


#  Herisson\Repository\BookmarkRepository:
#    factory: ['@doctrine.orm.default_entity_manager', getRepository]
#    arguments:
#      - Herisson\Entity\Bookmark

#  Herisson\Repository\HerissonRepository:
#    factory: ['@doctrine.orm.default_entity_manager', getRepository]
#    arguments:
#      - Herisson\Entity\Bookmark


#  Herisson\Repository\:
#    resource: '../src/Repository/'
#    tags: ['controller.service_arguments']
#    #calls:
#    #    - [setContainer, ["@service_container"]]


#  Herisson\UseCase\:
#    resource: '../src/UseCase/'
#    tags: ['controller.service_arguments']
#    #calls:
#    #    - [setContainer, ["@service_container"]]

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
